### PR TITLE
fix config

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by rmrhz** [comment]
@lloricode Why are you disabling the cipher list? This will have security implications if disabled given that the developer doesn't know how to implement proper infosec measures.

**Comment by rmrhz** [comment]
@lloricode you should explain that first in the OP before proposing such changes. Just update the thread.

**Comment by lloricode** [comment]
this is the return from sdk,
screenshot from 2018-07-16 06-53-24

then i try this from 
`HTTPConnection`
```php
if (curl_errno($session)) {

            dd(curl_error($session));

            $exception = new Exception("Error API call");
            curl_close($session);
            throw $exception;
}
```

it shows
screenshot from 2018-07-16 07-01-07


then this is the value of `$session`
screenshot from 2018-07-16 07-03-31

**Comment by lloricode** [comment]
hmmm maybe our SSL is issue, ?

**Comment by rmrhz** [comment]
I looked it up again and found out that the default value is not a valid cipher. Please use the following

```
ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
```

Assuming that you don't have backwards compatibility like users still on Windows XP / IE6. If so use the one below

```
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:DES-CBC3-SHA:HIGH:SEED:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!RSAPSK:!aDH:!aECDH:!EDH-DSS-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!SRP
```

**Pull request closed without merging**
